import { app, BrowserWindow } from 'electron';

import express from 'express';
import * as fs from 'fs';
import { readFile } from 'original-fs';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
  app.quit();
}

function readLocalFile(): string {
  return fs.readFileSync('C:/Users/weixzha/Desktop/hello.txt','utf8');
}

function StartHttpServer(): void {

  let app = express();
  app.get('/', (req, res) => {
    let data = readLocalFile();
    res.send('From Electron App leh. Data' + data)
  })

  app.listen(8090, () => {
    console.log(`Example app listening at http://localhost:${8090}`)
  })
}


const createWindow = (): void => {

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    maximizable: true,
    width: 1200,
    height: 1100,
    autoHideMenuBar: true,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

    StartHttpServer();

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
